name: Generate Lighthouse Badge
on:
  deployment:
  workflow_dispatch:
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Install lighthouse-badges
        run: npm install -g lighthouse-badges
      - name: Generate Badges
        run: lighthouse-badges --urls https://antoniohnz.me/ -o lighthouse_test_results
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: kings-league-bot
          author_email: ai@antoniohnz.me
          message: 'Update Lighthouse badges [skip ci]'
          add: 'lighthouse_test_results'
          push: true
          branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
